
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Dunno
{

using System;
    using System.Collections.Generic;
    
public partial class HocPhan
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public HocPhan()
    {

        this.MonHocs = new HashSet<MonHoc>();

    }


    public string MaHocPhan { get; set; }

    public string TenHocPhan { get; set; }

    public string MaLopHoc { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MonHoc> MonHocs { get; set; }

    public virtual LopHoc LopHoc { get; set; }

        public override string ToString()
        {
            return MaHocPhan;
        }

    }

}
