
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Dunno
{

using System;
    using System.Collections.Generic;
    
public partial class LopHoc
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public LopHoc()
    {

        this.HocViens = new HashSet<HocVien>();

        this.MonHocs = new HashSet<MonHoc>();

        this.BienLais = new HashSet<BienLai>();

        this.HocPhans = new HashSet<HocPhan>();

    }


    public string MaLopHoc { get; set; }

    public string TenLopHoc { get; set; }

    public string ThoiKhoaBieu { get; set; }

    public Nullable<System.DateTime> NgayKhaiGiang { get; set; }

    public Nullable<int> HocPhi { get; set; }

    public string LoaiLop { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HocVien> HocViens { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MonHoc> MonHocs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BienLai> BienLais { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HocPhan> HocPhans { get; set; }

        public override string ToString()
        {
            return MaLopHoc;
        }

    }

}
