
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Dunno
{

using System;
    using System.Collections.Generic;
    
public partial class MonHoc
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MonHoc()
    {

        this.DiemThis = new HashSet<DiemThi>();

    }


    public string MaMonHoc { get; set; }

    public string MaLopHoc { get; set; }

    public string TenMonHoc { get; set; }

    public Nullable<int> SoTietLyThuyet { get; set; }

    public Nullable<int> SoTietThucHanh { get; set; }

    public string MaHocPhan { get; set; }



    public virtual LopHoc LopHoc { get; set; }

    public virtual HocPhan HocPhan { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DiemThi> DiemThis { get; set; }

        public override string ToString()
        {
            return MaMonHoc;
        }

    }

}
